
/*
 * Copyright(c) Live2D Inc. All rights reserved.
 * 
 * Use of this source code is governed by the Live2D Open Software license
 * that can be found at http://live2d.com/eula/live2d-open-software-license-agreement_en.html.
 */

/* {{{autogeneratedwarning}}} */


namespace Live2D.Cubism.Core.Unmanaged
{
    /// <summary>
    /// <see cref="byte"/> extensions.
    /// </summary>
    internal static class ByteExtensionMethods
    {
        {{#flags}}
        {{#entries}}
        /// <summary>
        /// Checks whether flag is set.
        /// </summary>
        /// <param name="self">Bit field.</param>
        /// <returns><see langword="true"/> if bit is set; <see langword="false"/> otherwise.</returns>
        public static bool Has{{{Flagname}}}Flag(this byte self)
        {
            return (self & (1 << {{{flagindex}}})) == (1 << {{{flagindex}}});
        }
        
        {{/entries}}
        {{/flags}}
    }
}
