/*
 * Copyright(c) Live2D Inc. All rights reserved.
 * 
 * Use of this source code is governed by the Live2D Open Software license
 * that can be found at http://live2d.com/eula/live2d-open-software-license-agreement_en.html.
 */

/* {{{autogeneratedwarning}}} */


using System;
using System.Runtime.InteropServices;


namespace Live2D.Cubism.Core.Unmanaged
{
    /// <summary>
    /// Raw Core DLL bindings.
    /// </summary>
    public static class CubismCoreDll
    {
        /// <summary>
        /// Name of native DLL file.
        /// </summary>
#if (UNITY_IOS || UNITY_WEBGL || UNITY_SWITCH) && !UNITY_EDITOR
        public const string DllName = "__Internal";
#else
        public const string DllName = "Live2DCubismCore";
#endif
        {{#enums}}


        {{#entries}}
        /// <sumamry>
        /// {{{valuedoc}}}
        /// </sumamry>
        public const int {{{Valuename}}} = {{value}};
        {{/entries}}
        {{/enums}}
        {{#flags}}


        {{#entries}}
        /// <sumamry>
        /// {{{flagdoc}}}
        /// </sumamry>
        public const Byte {{{Flagname}}} = 1 << {{flagindex}};
        {{/entries}}
        {{/flags}}


        {{#dllentries}}
        /// <summary>
        /// {{{funcdoc}}}
        /// </summary>
        [DllImport(DllName, EntryPoint = "{{{entrypoint}}}")]
        public static extern {{{returntype}}} {{{funcname}}}({{{args}}});
        {{/dllentries}}
    }
}
